<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Maksim EstebanThu Jan 04 2024 152We nee_424938</name>
   <tag></tag>
   <elementGuidId>72cd625b-01cb-4e37-86a8-62cc32db7538</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/div[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Maksim EstebanThu Jan 04 2024 152We need to quantify the primary TCP matrix!Assu&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3d88313e-c36c-4cbe-9f98-6a432e539988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>article-preview</value>
      <webElementGuid>1a6e3649-6347-468b-a9e7-8a9b71345489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Maksim EstebanThu Jan 04 2024 152We need to quantify the primary TCP matrix!Assumenda molestiae laboriosam enim ipsum quaerat enim officia vel quo. Earum odit rem natus totam atque cumque. Sint dolorem facere non.Read more...repellatnostrumexcepturiquaerat</value>
      <webElementGuid>f3bdee31-5d49-4417-8f73-139d6d41a50d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;profile-page&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-md-10 offset-md-1&quot;]/div[2]/div[@class=&quot;article-preview&quot;]</value>
      <webElementGuid>6bbaec29-cd1d-4d50-9764-1b070c270480</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div[2]/div[5]</value>
      <webElementGuid>2089e631-54d1-4ed3-8f31-b1db97eddd20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='neque'])[2]/following::div[1]</value>
      <webElementGuid>23447b4d-59b2-4406-9dc7-4e09c41ed70d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='consequatur'])[1]/following::div[1]</value>
      <webElementGuid>f6132fdc-a3cf-475e-b14e-73a2d2c51d63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]</value>
      <webElementGuid>617ef09b-703e-447d-ae81-bd540da12f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Maksim EstebanThu Jan 04 2024 152We need to quantify the primary TCP matrix!Assumenda molestiae laboriosam enim ipsum quaerat enim officia vel quo. Earum odit rem natus totam atque cumque. Sint dolorem facere non.Read more...repellatnostrumexcepturiquaerat' or . = 'Maksim EstebanThu Jan 04 2024 152We need to quantify the primary TCP matrix!Assumenda molestiae laboriosam enim ipsum quaerat enim officia vel quo. Earum odit rem natus totam atque cumque. Sint dolorem facere non.Read more...repellatnostrumexcepturiquaerat')]</value>
      <webElementGuid>7f8125b2-06ec-4b37-9a39-599eabd067a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
