<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Your SettingsUpdate SettingsOr click he_e856d0</name>
   <tag></tag>
   <elementGuidId>cf5b2f6d-154d-42fc-aa7c-f123ca1ef4e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-6.offset-md-3.col-xs-12</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Your SettingsUpdate SettingsOr click here to logout.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9c3e8a45-6840-4525-8e71-3451be00b59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-6 offset-md-3 col-xs-12</value>
      <webElementGuid>ff73a123-d6cd-4127-b813-7651e8495a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your SettingsUpdate SettingsOr click here to logout.</value>
      <webElementGuid>b26fd394-2354-43cc-a675-6eda92224808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;settings-page&quot;]/div[@class=&quot;container page&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 offset-md-3 col-xs-12&quot;]</value>
      <webElementGuid>829ae6bc-b238-4bca-9914-f03b9a2b3c53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div</value>
      <webElementGuid>f63259b4-9829-4738-a33e-67a0eee23ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dang'])[1]/following::div[4]</value>
      <webElementGuid>55e97e26-c71e-4d1d-af82-e10aa72ec8e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div</value>
      <webElementGuid>52835a3a-472c-40e0-bbe4-9b9f9eb8fb01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Your SettingsUpdate SettingsOr click here to logout.' or . = 'Your SettingsUpdate SettingsOr click here to logout.')]</value>
      <webElementGuid>ccb8624a-376f-4c46-930c-d15949cd1d35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
