name: CI/CD

# Xác định sự kiện trigger cho pipeline, trong trường hợp này là push lên nhánh develop
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
env:
  PORT: 8000
permissions:
  contents: write

    
  

# Định nghĩa các jobs cần thực hiện 
jobs:

  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and test
        run: |
          docker build -t demo-react-app .
          docker run demo-react-app npm run build
      - name: Push image to Docker Hub
        uses: docker/build-push-action@v2
        # Sử dụng action "docker/build-push-action" để đẩy image lên Docker Hub
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/demo-react-app:lastest${{ github.sha }}
  deploy:
        needs: build_and_test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
                  publish_branch: gh-pages
  test:
        # needs: deploy
        runs-on: windows-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        # - name: Download ChromeDriver
        #   run: |
        #       curl -L https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.109/win32/chromedriver-win32.zip -o chromedriver.zip
        # - name: Unzip ChromeDriver
        #   run: |
        #       unzip chromedriver.zip
        
        - name: Katalon Studio Github Action
          uses: katalon-studio/katalon-studio-github-action@v3.0
          with:
              version: '9.5.0'
              projectPath: ${{ github.workspace }}/test
              args: '-retry=0 -testSuitePath="Test Suites/New Test Suite" -apiKey="b882ef65-7d47-4f1e-b0ab-1cba4ba478f3" -browserType="Firefox" -executionProfile="default" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true'
        - name: Upload Reports
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: Katalon Reports
            path: ${{ github.workspace }}/Reports/**/*

  notify_slack:
       needs: test
       if: failure()
       runs-on: ubuntu-latest
       steps:
      
     
        - uses: actions/checkout@v2
        - name: Slack Notification
          uses: rtCamp/action-slack-notify@v2
          env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        - name: Slack Notification
          uses: rtCamp/action-slack-notify@v2
          env:
            SLACK_CHANNEL: project
            SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
            SLACK_ICON: https://github.com/rtCamp.png?size=48
            SLACK_MESSAGE: 'Test failed !'
            SLACK_TITLE: Workflow Status
            SLACK_USERNAME: project github
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
      





