name: mini test
# Xác định sự kiện trigger cho pipeline, trong trường hợp này là push lên nhánh develop
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
env:
  PORT: 8000
permissions:
  contents: write

    
  

# Định nghĩa các jobs cần thực hiện 
jobs:
   # Job 1: build và test
   # Job thực thi trên máy ảo ubuntu
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        # Sử dụng action "checkout" để sao copy code từ repository vào máy ảo Ubuntu
        uses: actions/checkout@v2

      - name: Login to Docker Hub
          # Sử dụng action "docker/login-action" để đăng nhập vào Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and test
        # Build và test image được build ra bằng Docker 
        run: |
          docker build -t demo-react-app .
          docker run demo-react-app npm run build
      - name: Push image to Docker Hub
        uses: docker/build-push-action@v2
        # Sử dụng action "docker/build-push-action" để đẩy image lên Docker Hub
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/demo-react-app:lastest${{ github.sha }}
  deploy:
        needs: build_and_test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
                  publish_branch: gh-pages
  test:
        needs: deploy
        runs-on: windows-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Download ChromeDriver
          run: |
              curl -L https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.109/win32/chromedriver-win32.zip -o chromedriver.zip
        - name: Unzip ChromeDriver
          run: |
              unzip chromedriver.zip
        
        - name: Katalon Studio Github Action
          uses: katalon-studio/katalon-studio-github-action@v3.0
          with:
              version: '9.5.0'
              projectPath: ${{ github.workspace }}/test
              args: ' -retry=0 -testSuitePath="Test Suites/mini" -apiKey="b882ef65-7d47-4f1e-b0ab-1cba4ba478f3" -browserType="Chrome" -executionProfile="default" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true -sendMail="20120263@student.hcmus.edu.vn" '
  notify_slack:
       needs: deploy
       if: failure()

       runs-on: ubuntu-latest
       steps:
       - name: Send Slack notification
         uses: 8398a7/action-slack@v3
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
         with:
           status: custom
           fields: repo,commit,event,action,workflow,ref,URL
           custom_payload: |
               {
                 "attachments": [
                   {
                     "color": "${{ job.status }}",
                     "title": >-
                       ${{ github.actor }} ${{ github.event.pull_request && github.event.pull_request.merged == true && 'merged a pull request' || github.event.pull_request && 'opened a pull request' || github.event_name == 'push' && 'pushed new changes' || github.event_name == 'create' && 'created a new branch or tag' || github.event_name == 'delete' && 'deleted a branch or tag' || github.event_name == 'issues' && github.event.action || 'triggered an event' }},
                     "text": >-
                       :tada: Event details:
                      
                       - Repository: ${{ github.repository }}
                       - Branch: ${{ github.ref }}
                       - Message: ${{ github.event_name == 'push' && github.event.head_commit.message || github.event_name == 'issues' && github.event.issue.title || github.event_name == 'pull_request' && github.event.pull_request.title || '' }}
                       - :globe_with_meridians: Link: ${{ github.event.pull_request.html_url || github.event.issue.html_url || github.event.repository.html_url }}
                   }
                  
                 ]
               }

        
    
